name: update

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Use Node js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: download dependencies
      run: npm install
      
    - name: run eslint with prettier
      run: npm run lint
      
    - name: test dev
      run: npm run dev

    - name: test backend
      run: npm run start
